### ISSUE TITLE
Crash when logging in to discord app.

### ISSUE THREAD

**Issue by VanillaChan6571** [grillo78/Apps-Mod#1]
Crash Log:
https://hastebin.com/horoxaqohi.rb

**Comment by grillo78** [comment]
I will fix it in the next update

**Comment by grillo78** [comment]
can you re-send the crash log but using pastebin?

**Comment by SimonYuuki** [comment]
me too that does it to me!

**Comment by SimonYuuki** [comment]
crash log : ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OTGCorePlugin (OTG-Core.jar)
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/3/19 12:15 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: org/apache/commons/collections4/map/CaseInsensitiveMap
	at net.dv8tion.jda.core.utils.JDALogger.<clinit>(JDALogger.java:57)
	at net.dv8tion.jda.core.entities.impl.JDAImpl.<clinit>(JDAImpl.java:65)
	at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:890)
	at com.grillo78.appsmod.handler.DiscordEventHandler.loginWithCredentiasl(DiscordEventHandler.java:167)
	at com.grillo78.appsmod.programs.ApplicationDiscord.lambda$init$0(ApplicationDiscord.java:79)
	at com.grillo78.appsmod.programs.ApplicationDiscord$$Lambda$868/1979237850.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:278)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:238)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:162)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:204)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:323)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.map.CaseInsensitiveMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.dv8tion.jda.core.utils.JDALogger.<clinit>(JDALogger.java:57)
	at net.dv8tion.jda.core.entities.impl.JDAImpl.<clinit>(JDAImpl.java:65)
	at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:890)
	at com.grillo78.appsmod.handler.DiscordEventHandler.loginWithCredentiasl(DiscordEventHandler.java:167)
	at com.grillo78.appsmod.programs.ApplicationDiscord.lambda$init$0(ApplicationDiscord.java:79)
	at com.grillo78.appsmod.programs.ApplicationDiscord$$Lambda$868/1979237850.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:278)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:238)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:162)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:204)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:323)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.device.core.Laptop

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Simon_Yuuki'/31, l='MpServer', x=-429.50, y=4.15, z=36.50]]
	Chunk stats: MultiplayerChunkCache: 288, 288
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-475,4,10), Chunk: (at 5,0,10 in -30,0; contains blocks -480,0,0 to -465,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13165 game time, 13165 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntitySeat['entity.Seat.name'/517, l='MpServer', x=-429.50, y=4.50, z=36.50], EntityItem['item.item.beetroot'/777, l='MpServer', x=-440.86, y=5.00, z=82.45], EntityVillager['Villageois'/10, l='MpServer', x=-496.49, y=5.00, z=48.70], EntityVillager['Villageois'/11, l='MpServer', x=-496.49, y=5.00, z=48.50], EntityItem['item.item.beetroot_seeds'/779, l='MpServer', x=-440.58, y=5.00, z=81.98], EntityVillager['Villageois'/12, l='MpServer', x=-489.16, y=5.00, z=79.99], EntityVillager['Villageois'/13, l='MpServer', x=-490.14, y=5.00, z=79.88], EntityVillager['Villageois'/14, l='MpServer', x=-468.70, y=7.00, z=33.70], EntityVillager['Villageois'/15, l='MpServer', x=-498.76, y=5.00, z=48.26], EntityVillager['Villageois'/16, l='MpServer', x=-496.49, y=5.00, z=48.30], EntityVillager['Villageois'/17, l='MpServer', x=-468.59, y=5.00, z=70.92], EntityVillager['Villageois'/18, l='MpServer', x=-490.21, y=5.00, z=79.02], EntityVillager['Villageois'/19, l='MpServer', x=-484.30, y=5.00, z=79.69], EntityVillager['Villageois'/20, l='MpServer', x=-476.18, y=5.00, z=71.01], EntityVillager['Villageois'/21, l='MpServer', x=-473.50, y=5.00, z=79.93], EntityItem['item.item.seeds'/789, l='MpServer', x=-444.02, y=4.94, z=79.53], EntityVillager['Villageois'/22, l='MpServer', x=-467.14, y=5.00, z=47.44], EntityVillager['Villageois'/23, l='MpServer', x=-488.50, y=5.00, z=56.93], EntityVillager['Villageois'/24, l='MpServer', x=-469.30, y=5.00, z=71.07], EntityVillager['Villageois'/25, l='MpServer', x=-463.93, y=5.00, z=32.50], EntityVillager['Villageois'/26, l='MpServer', x=-462.30, y=5.00, z=31.30], EntityItem['item.item.potato'/794, l='MpServer', x=-439.51, y=5.00, z=72.95], EntityVillager['Villageois'/27, l='MpServer', x=-454.08, y=5.00, z=36.29], EntityVillager['Villageois'/28, l='MpServer', x=-469.70, y=5.00, z=72.00], EntityVillager['Villageois'/29, l='MpServer', x=-469.67, y=5.00, z=70.21], EntityVillager['Villageois'/30, l='MpServer', x=-452.70, y=4.00, z=61.16], EntityItem['item.item.beetroot_seeds'/799, l='MpServer', x=-441.14, y=4.94, z=79.21], EntitySkeleton['Squelette'/32, l='MpServer', x=-467.50, y=5.00, z=70.50], EntitySpider['AraignÃ©e'/34, l='MpServer', x=-490.08, y=5.00, z=81.10], EntityItem['item.item.carrots'/804, l='MpServer', x=-448.36, y=5.00, z=68.97], EntityBabySkeleton['BÃ©bÃ© squelette'/37, l='MpServer', x=-453.50, y=5.00, z=38.50], EntityPlayerSP['Simon_Yuuki'/31, l='MpServer', x=-429.50, y=4.15, z=36.50], EntityItem['item.item.carrots'/810, l='MpServer', x=-452.47, y=4.94, z=69.73], EntityLatchedRenderer['inconnu'/43, l='MpServer', x=8.50, y=65.00, z=8.50], EntityItem['item.item.wheat'/813, l='MpServer', x=-443.53, y=5.00, z=80.68], EntityItem['item.item.carrots'/815, l='MpServer', x=-453.52, y=5.00, z=67.80], EntitySlime['Slime'/827, l='MpServer', x=-385.66, y=4.00, z=101.43], EntitySlime['Slime'/848, l='MpServer', x=-380.26, y=4.14, z=74.08], EntityItem['item.item.beetroot_seeds'/598, l='MpServer', x=-441.66, y=4.94, z=81.44], EntitySlime['Slime'/854, l='MpServer', x=-397.39, y=4.00, z=100.16], EntitySlime['Slime'/733, l='MpServer', x=-354.75, y=4.00, z=26.96], EntitySlime['Slime'/734, l='MpServer', x=-426.82, y=5.17, z=46.90], EntitySlime['Slime'/864, l='MpServer', x=-371.92, y=4.00, z=97.11], EntitySlime['Slime'/870, l='MpServer', x=-409.41, y=4.00, z=107.53], EntityBabySkeleton['BÃ©bÃ© squelette'/871, l='MpServer', x=-488.50, y=5.00, z=85.50], EntityZombie['Zombie'/873, l='MpServer', x=-475.30, y=5.00, z=57.30], EntitySlime['Slime'/364, l='MpServer', x=-431.27, y=4.36, z=27.10], EntitySlime['Slime'/876, l='MpServer', x=-376.03, y=4.00, z=2.24], EntityItem['item.item.seeds'/753, l='MpServer', x=-430.78, y=5.00, z=70.52], EntityItem['item.item.wheat'/756, l='MpServer', x=-431.19, y=5.00, z=69.56], EntityItem['item.item.seeds'/757, l='MpServer', x=-430.92, y=5.00, z=69.16], EntityItem['item.item.seeds'/758, l='MpServer', x=-431.95, y=4.94, z=70.19]]
	Retry entities: 1 total; [EntityLatchedRenderer['inconnu'/43, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1435198920 bytes (1368 MB) / 2717908992 bytes (2592 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2826 Optifine OptiFine_1.12.2_HD_U_F4 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                         | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2826.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2826             | forge-1.12.2-14.23.5.2826.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore                                      | 1.12.2 - v8_r8           | minecraft.jar                                  | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                  | None                                     |
	| LCHIJA | dsurroundcore                                | 3.5.5.0                  | minecraft.jar                                  | None                                     |
	| LCHIJA | antiqueatlas                                 | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay                          | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | cdm                                          | 0.4.1                    | cdm-0.4.1-mc1.12.2.jar                         | None                                     |
	| LCHIJA | mcef                                         | 1.11                     | mcef-1.12.2-1.11.jar                           | None                                     |
	| LCHIJA | appsmod                                      | 1.7.2                    | appsmod-1.7.2.jar                              | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCHIJA | bubble_burst                                 | 3.1                      | BubbleBurst-3.1.jar                            | None                                     |
	| LCHIJA | carryon                                      | 1.12.2                   | CarryOn+MC1.12.2+v1.12.2.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | chunkanimator                                | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCHIJA | comforts                                     | 1.4.1.2                  | comforts-1.12.2-1.4.1.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | coralreef                                    | 2.0                      | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| LCHIJA | craftablehorsearmour                         | 1.3                      | CraftableHorseArmour-1.3.0-1.12.jar            | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| LCHIJA | grapplemod                                   | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jei                                          | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | mekanism                                     | 1.12.2-9.8.2.389         | Mekanism-1.12.2-9.8.2.389.jar                  | None                                     |
	| LCHIJA | mekanismgenerators                           | 1.12.2-9.8.2.389         | MekanismGenerators-1.12.2-9.8.2.389.jar        | None                                     |
	| LCHIJA | mekanismtools                                | 1.12.2-9.8.2.389         | MekanismTools-1.12.2-9.8.2.389.jar             | None                                     |
	| LCHIJA | waystones                                    | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                    | None                                     |
	| LCHIJA | wearablebackpacks                            | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCHIJA | orelib                                       | 3.5.2.3                  | OreLib-1.12.2-3.5.2.3.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.5.5.0                  | DynamicSurroundings-1.12.2-3.5.5.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dshuds                                       | 3.5.4.0                  | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
  mekanism.coremod.KeybindingMigrationHelper
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  org.orecruncher.dsurround.asm.Transformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 7400M Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2826
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7400M Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: FranÃ§ais (France)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.21 Lite.zip
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 7400M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
